from .utils import validate_with_schema, im, im_ns
from .fetch_rack_slot_type_by_project_list_schema import FetchRackSlotTypeByProjectListSchema
from .query_stb_info_schema import QueryStbInfoSchema
from .get_stb_status_broken_schema import GetStbStatusBrokenSchema
from .get_broken_from_rack_schema import GetBrokenFromRackSchema
from .get_rack_slot_by_ip_schema import GetRackSlotByIpSchema
from .available_slots_schema import AvailableSlotsSchema
from .get_ip_schema import GetIpSchema
from .get_stbs_by_project_schema import GetStbsByProjectSchema
from .fetch_rack_slot_type_by_project_schema import FetchRackSlotTypeByProjectSchema
from .fetch_slots_versions_schema import FetchSlotVersionsSchema
from .fetch_rack_slots_by_project_and_type_schema import FetchRackSlotByProjectAndTypeSchema
from .fetch_rack_slot_type_by_project_grouped_by_rack_schema import FetchRackSlotTypeByProjectGroupedByRackSchema
from .fetch_rack_slot_by_project_and_type_grouped_by_rack_schema import FetchRackSlotByProjectAndTypeGroupedByRackSchema